services:
  frontend:
    container_name: ${APP_NAME}_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    ports:
      - ${FRONTEND_PORT}:3000
      - ${FRONTEND_HMR_PORT}:3010
    volumes:
      - ./frontend:/frontend
      - ./biome.json:/biome.json
      - ./.gitignore:/.gitignore
      - ./.env:/.env

  backend:
    container_name: ${APP_NAME}_backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./backend:/backend
      - ./biome.json:/biome.json
      - ./.gitignore:/.gitignore
      - ./.env:/.env
      - ./database/db.d.ts:/database/db.d.ts

  database:
    container_name: ${APP_NAME}_database
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}@postgres:5432/${POSTGRES_DATABASE}?sslmode=disable
    volumes:
      - ./database:/database
      - ./.env:/.env

  storybook:
    container_name: ${APP_NAME}_storybook
    build:
      context: frontend
      dockerfile: Dockerfile.storybook
    env_file:
      - .env
    stdin_open: true
    ports:
      - ${STORYBOOK_PORT}:3000
      - ${STORYBOOK_HMR_PORT}:3010
    volumes:
      - ./frontend:/storybook
      - ./.env:/.env

  mails:
    container_name: ${APP_NAME}_mails
    build:
      context: mails
      dockerfile: Dockerfile
    ports:
      - ${MAILS_PORT}:3000
    volumes:
      - ./mails:/mails
      - ./.env:/.env
      - ./biome.json:/biome.json
      - ./.gitignore:/.gitignore

  mailpit:
    container_name: ${APP_NAME}_mailpit
    image: axllent/mailpit
    ports:
      - ${MAILPIT_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025

  postgres:
    container_name: ${APP_NAME}_postgres
    image: postgres:17
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
