// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { deleteSignOut, getHealth, getProfile, getReady, getSessions, getSessionsById, getUsers, getUsersById, type Options, postSignIn, postSignUp } from '../sdk.gen';
import type { DeleteSignOutData, GetHealthData, GetHealthResponse, GetProfileData, GetProfileResponse, GetReadyData, GetReadyResponse, GetSessionsByIdData, GetSessionsByIdResponse, GetSessionsData, GetSessionsResponse, GetUsersByIdData, GetUsersByIdResponse, GetUsersData, GetUsersResponse, PostSignInData, PostSignInResponse, PostSignUpData, PostSignUpResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProfileQueryKey = (options?: Options<GetProfileData>) => createQueryKey('getProfile', options);

/**
 * Returns the profile of the signed in user
 */
export const getProfileOptions = (options?: Options<GetProfileData>) => queryOptions<GetProfileResponse, AxiosError<DefaultError>, GetProfileResponse, ReturnType<typeof getProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProfileQueryKey(options)
});

/**
 *
 * Creates a new user account with the provided credentials.
 *
 * - Accepts first name, last name, email, and password.
 * - Automatically signs the user in after registration.
 * - Returns the created user's profile and sets a session cookie in the response headers.
 *
 */
export const postSignUpMutation = (options?: Partial<Options<PostSignUpData>>): UseMutationOptions<PostSignUpResponse, AxiosError<DefaultError>, Options<PostSignUpData>> => {
    const mutationOptions: UseMutationOptions<PostSignUpResponse, AxiosError<DefaultError>, Options<PostSignUpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postSignUp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 *
 * Signs out the currently authenticated user by invalidating the session token and deleting the session.
 *
 */
export const deleteSignOutMutation = (options?: Partial<Options<DeleteSignOutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteSignOutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteSignOutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteSignOut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 *
 * Signs out the currently authenticated user by invalidating the session token.
 *
 */
export const postSignInMutation = (options?: Partial<Options<PostSignInData>>): UseMutationOptions<PostSignInResponse, AxiosError<DefaultError>, Options<PostSignInData>> => {
    const mutationOptions: UseMutationOptions<PostSignInResponse, AxiosError<DefaultError>, Options<PostSignInData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postSignIn({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSessionsQueryKey = (options?: Options<GetSessionsData>) => createQueryKey('getSessions', options);

/**
 * Returns list of all sessions
 */
export const getSessionsOptions = (options?: Options<GetSessionsData>) => queryOptions<GetSessionsResponse, AxiosError<DefaultError>, GetSessionsResponse, ReturnType<typeof getSessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getSessionsInfiniteQueryKey = (options?: Options<GetSessionsData>): QueryKey<Options<GetSessionsData>> => createQueryKey('getSessions', options, true);

/**
 * Returns list of all sessions
 */
export const getSessionsInfiniteOptions = (options?: Options<GetSessionsData>) => infiniteQueryOptions<GetSessionsResponse, AxiosError<DefaultError>, InfiniteData<GetSessionsResponse>, QueryKey<Options<GetSessionsData>>, number | Pick<QueryKey<Options<GetSessionsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetSessionsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getSessions({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionsInfiniteQueryKey(options)
});

export const getSessionsByIdQueryKey = (options: Options<GetSessionsByIdData>) => createQueryKey('getSessionsById', options);

/**
 * Returns sessions for given id
 */
export const getSessionsByIdOptions = (options: Options<GetSessionsByIdData>) => queryOptions<GetSessionsByIdResponse, AxiosError<DefaultError>, GetSessionsByIdResponse, ReturnType<typeof getSessionsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSessionsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionsByIdQueryKey(options)
});

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * Returns a list of all users.
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => queryOptions<GetUsersResponse, AxiosError<DefaultError>, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});

export const getUsersInfiniteQueryKey = (options?: Options<GetUsersData>): QueryKey<Options<GetUsersData>> => createQueryKey('getUsers', options, true);

/**
 * Returns a list of all users.
 */
export const getUsersInfiniteOptions = (options?: Options<GetUsersData>) => infiniteQueryOptions<GetUsersResponse, AxiosError<DefaultError>, InfiniteData<GetUsersResponse>, QueryKey<Options<GetUsersData>>, number | Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getUsers({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersInfiniteQueryKey(options)
});

export const getUsersByIdQueryKey = (options: Options<GetUsersByIdData>) => createQueryKey('getUsersById', options);

/**
 * Returns the user matching the given id
 */
export const getUsersByIdOptions = (options: Options<GetUsersByIdData>) => queryOptions<GetUsersByIdResponse, AxiosError<DefaultError>, GetUsersByIdResponse, ReturnType<typeof getUsersByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsersById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersByIdQueryKey(options)
});

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, AxiosError<DefaultError>, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getReadyQueryKey = (options?: Options<GetReadyData>) => createQueryKey('getReady', options);

export const getReadyOptions = (options?: Options<GetReadyData>) => queryOptions<GetReadyResponse, AxiosError<DefaultError>, GetReadyResponse, ReturnType<typeof getReadyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getReady({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getReadyQueryKey(options)
});
