// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteSignOutData, GetHealthData, GetHealthResponses, GetProfileData, GetProfileResponses, GetReadyData, GetReadyResponses, GetSessionsByIdData, GetSessionsByIdResponses, GetSessionsData, GetSessionsResponses, GetUsersByIdData, GetUsersByIdResponses, GetUsersData, GetUsersResponses, PostSignInData, PostSignInResponses, PostSignUpData, PostSignUpResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the profile of the signed in user
 */
export const getProfile = <ThrowOnError extends boolean = false>(options?: Options<GetProfileData, ThrowOnError>) => (options?.client ?? client).get<GetProfileResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/profile',
    ...options
});

/**
 *
 * Creates a new user account with the provided credentials.
 *
 * - Accepts first name, last name, email, and password.
 * - Automatically signs the user in after registration.
 * - Returns the created user's profile and sets a session cookie in the response headers.
 *
 */
export const postSignUp = <ThrowOnError extends boolean = false>(options?: Options<PostSignUpData, ThrowOnError>) => (options?.client ?? client).post<PostSignUpResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/sign_up',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 *
 * Signs out the currently authenticated user by invalidating the session token and deleting the session.
 *
 */
export const deleteSignOut = <ThrowOnError extends boolean = false>(options?: Options<DeleteSignOutData, ThrowOnError>) => (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({ url: '/sign_out', ...options });

/**
 *
 * Signs out the currently authenticated user by invalidating the session token.
 *
 */
export const postSignIn = <ThrowOnError extends boolean = false>(options?: Options<PostSignInData, ThrowOnError>) => (options?.client ?? client).post<PostSignInResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/sign_in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Returns list of all sessions
 */
export const getSessions = <ThrowOnError extends boolean = false>(options?: Options<GetSessionsData, ThrowOnError>) => (options?.client ?? client).get<GetSessionsResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { orderBy: { object: { style: 'form' } }, where: { object: { style: 'form' } } } },
    responseType: 'json',
    url: '/sessions',
    ...options
});

/**
 * Returns sessions for given id
 */
export const getSessionsById = <ThrowOnError extends boolean = false>(options: Options<GetSessionsByIdData, ThrowOnError>) => (options.client ?? client).get<GetSessionsByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/sessions/{id}',
    ...options
});

/**
 * Returns a list of all users.
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { orderBy: { object: { style: 'form' } }, where: { object: { style: 'form' } } } },
    responseType: 'json',
    url: '/users',
    ...options
});

/**
 * Returns the user matching the given id
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/users/{id}',
    ...options
});

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

export const getReady = <ThrowOnError extends boolean = false>(options?: Options<GetReadyData, ThrowOnError>) => (options?.client ?? client).get<GetReadyResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ready',
    ...options
});
