// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profile';
};

export type GetProfileResponses = {
    200: {
        user: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            role: 'user' | 'admin';
            createdAt: string;
            updatedAt: string;
        };
        rules: Array<{
            action: string;
            subject: string;
            conditions?: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type PostSignUpData = {
    body?: {
        firstName: string;
        lastName: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/sign_up';
};

export type PostSignUpResponses = {
    201: {
        user: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            role: 'user' | 'admin';
            createdAt: string;
            updatedAt: string;
        };
        rules: Array<{
            action: string;
            subject: string;
            conditions?: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type PostSignUpResponse = PostSignUpResponses[keyof PostSignUpResponses];

export type DeleteSignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sign_out';
};

export type PostSignInData = {
    body?: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/sign_in';
};

export type PostSignInResponses = {
    201: {
        user: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            role: 'user' | 'admin';
            createdAt: string;
            updatedAt: string;
        };
        rules: Array<{
            action: string;
            subject: string;
            conditions?: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type PostSignInResponse = PostSignInResponses[keyof PostSignInResponses];

export type GetSessionsData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
        orderBy?: {
            id?: 'asc' | 'desc';
            userId?: 'asc' | 'desc';
            expiresAt?: 'asc' | 'desc';
            createdAt?: 'asc' | 'desc';
            updatedAt?: 'asc' | 'desc';
        };
        where?: {
            id?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            userId?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            expiresAt?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            createdAt?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            updatedAt?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
        };
    };
    url: '/sessions';
};

export type GetSessionsResponses = {
    200: {
        data: Array<{
            id: string;
            userId: string;
            expiresAt: string;
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        offset?: number;
        limit?: number;
        orderBy?: {
            id?: 'asc' | 'desc';
            userId?: 'asc' | 'desc';
            expiresAt?: 'asc' | 'desc';
            createdAt?: 'asc' | 'desc';
            updatedAt?: 'asc' | 'desc';
        };
    };
};

export type GetSessionsResponse = GetSessionsResponses[keyof GetSessionsResponses];

export type GetSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sessions/{id}';
};

export type GetSessionsByIdResponses = {
    200: {
        id: string;
        userId: string;
        expiresAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetSessionsByIdResponse = GetSessionsByIdResponses[keyof GetSessionsByIdResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        offset?: number;
        limit?: number;
        orderBy?: {
            id?: 'asc' | 'desc';
            firstName?: 'asc' | 'desc';
            lastName?: 'asc' | 'desc';
            email?: 'asc' | 'desc';
            role?: 'asc' | 'desc';
            createdAt?: 'asc' | 'desc';
            updatedAt?: 'asc' | 'desc';
        };
        where?: {
            id?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            firstName?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            lastName?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            email?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            role?: {
                $match: 'user' | 'admin';
                $eq: 'user' | 'admin';
                $ne: 'user' | 'admin';
                $lt: 'user' | 'admin';
                $lte: 'user' | 'admin';
                $gt: 'user' | 'admin';
                $gte: 'user' | 'admin';
                $in: Array<'user' | 'admin'> | null;
                $nin: Array<'user' | 'admin'> | null;
            } | 'user' | 'admin';
            createdAt?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
            updatedAt?: {
                $match: string | null;
                $eq: string | null;
                $ne: string | null;
                $lt: string | null;
                $lte: string | null;
                $gt: string | null;
                $gte: string | null;
                $in: Array<string> | null;
                $nin: Array<string> | null;
            } | string | null;
        };
    };
    url: '/users';
};

export type GetUsersResponses = {
    200: {
        data: Array<{
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            role: 'user' | 'admin';
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
        offset?: number;
        limit?: number;
        orderBy?: {
            id?: 'asc' | 'desc';
            firstName?: 'asc' | 'desc';
            lastName?: 'asc' | 'desc';
            email?: 'asc' | 'desc';
            role?: 'asc' | 'desc';
            createdAt?: 'asc' | 'desc';
            updatedAt?: 'asc' | 'desc';
        };
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdResponses = {
    200: {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        role: 'user' | 'admin';
        createdAt: string;
        updatedAt: string;
    };
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    200: {
        httpServer: {
            ok: boolean;
            sessions?: number;
        };
        postgres: {
            ok: true;
            connections: number;
        } | {
            ok: false;
        };
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type GetReadyResponses = {
    200: {
        status: 'ready' | 'degraded';
        services: {
            postgres: boolean;
        };
    };
};

export type GetReadyResponse = GetReadyResponses[keyof GetReadyResponses];
