/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Sessions {
  createdAt: Generated<Timestamp>
  expiresAt: Timestamp
  hashedToken: string
  id: Generated<string>
  updatedAt: Generated<Timestamp>
  userId: string
}

export interface Users {
  createdAt: Generated<Timestamp>
  email: string
  firstName: string
  id: Generated<string>
  lastName: string
  password: string
  updatedAt: Generated<Timestamp>
}

export interface UserSessions {
  createdAt: Generated<Timestamp>
  expiresAt: Timestamp
  hashedToken: string
  id: Generated<string>
  updatedAt: Generated<Timestamp>
  userId: string
}

export interface DB {
  sessions: Sessions
  users: Users
  userSessions: UserSessions
}
