const HttpHeader = {
  ACCEPT: "Accept",
  ACCEPT_ENCODING: "Accept-Encoding",
  ACCEPT_LANGUAGE: "Accept-Language",
  AUTHORIZATION: "Authorization",
  CACHE_CONTROL: "Cache-Control",
  CONNECTION: "Connection",
  CONTENT_DISPOSITION: "Content-Disposition",
  CONTENT_ENCODING: "Content-Encoding",
  CONTENT_LANGUAGE: "Content-Language",
  CONTENT_LENGTH: "Content-Length",
  CONTENT_LOCATION: "Content-Location",
  CONTENT_RANGE: "Content-Range",
  CONTENT_TYPE: "Content-Type",
  DATE: "Date",
  EXPECT: "Expect",
  FROM: "From",
  HOST: "Host",
  IF_MATCH: "If-Match",
  IF_MODIFIED_SINCE: "If-Modified-Since",
  IF_NONE_MATCH: "If-None-Match",
  IF_RANGE: "If-Range",
  IF_UNMODIFIED_SINCE: "If-Unmodified-Since",
  LAST_MODIFIED: "Last-Modified",
  LOCATION: "Location",
  MAX_FORWARDS: "Max-Forwards",
  ORIGIN: "Origin",
  PRAGMA: "Pragma",
  PROXY_AUTHORIZATION: "Proxy-Authorization",
  RANGE: "Range",
  REFERER: "Referer",
  SET_COOKIE: "Set-Cookie",
  TE: "TE",
  TRANSFER_ENCODING: "Transfer-Encoding",
  UPGRADE: "Upgrade",
  USER_AGENT: "User-Agent",
  VARY: "Vary",
  VIA: "Via",
  WARNING: "Warning",
  WWW_AUTHENTICATE: "WWW-Authenticate",
} as const

type HttpHeader = (typeof HttpHeader)[keyof typeof HttpHeader]
export default HttpHeader
