name: Lint, build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      database: ${{ steps.filter.outputs.database }}
      mails: ${{ steps.filter.outputs.mails }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            database:
              - 'database/migrations/**'
            mails:
              - 'mails/**'

  mails-lint:
    needs: changes
    if: ${{ needs.changes.outputs.mails == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: mails/package-lock.json
      - uses: actions/cache@v4
        with:
          path: "mails/node_modules"
          key: ${{ runner.os }}-mails-node-modules-${{ hashFiles('mails/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-mails-node-modules-${{ hashFiles('mails/package-lock.json') }}
            ${{ runner.os }}-mails-node-modules-
      - name: npm run lint
        run: |
          cd mails
          npm ci
          npm run lint

  frontend-lint:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - uses: actions/cache@v4
        with:
          path: "frontend/node_modules"
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
            ${{ runner.os }}-frontend-node-modules-
      - name: npm run lint
        run: |
          cd frontend
          npm ci
          npm run lint

  frontend-build:
    runs-on: ubuntu-latest
    needs: frontend-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - uses: actions/cache/restore@v4
        with:
          path: "frontend/node_modules"
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: npm run build
        run: |
          cd frontend
          npm run build
        env:
          VITE_EXAMPLE: example

  frontend-test:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - uses: actions/cache/restore@v4
        with:
          path: "frontend/node_modules"
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: npm test
        run: |
          cd frontend
          npm test
        env:
          VITE_EXAMPLE: example

  backend-lint:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - uses: actions/cache@v4
        with:
          path: "backend/node_modules"
          key: ${{ runner.os }}-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
            ${{ runner.os }}-backend-node-modules-
      - name: npm run lint
        run: |
          cd backend
          npm ci
          npm run lint

  backend-build:
    runs-on: ubuntu-latest
    needs: backend-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - uses: actions/cache/restore@v4
        with:
          path: "backend/node_modules"
          key: ${{ runner.os }}-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: npm run build
        run: |
          cd backend
          npm run build
        env:
          VITE_EXAMPLE: example

  backend-test:
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - uses: actions/cache/restore@v4
        with:
          path: "backend/node_modules"
          key: ${{ runner.os }}-backend-node-modules-${{ hashFiles('backend/package-lock.json') }}
          fail-on-cache-miss: true
      - name: npm test
        run: |
          cd backend
          npm test
        env:
          VITE_EXAMPLE: example

  database-migrations:
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.database == 'true' }}
    needs: changes
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: run migrations
        run: |
          cd database
          npm ci
          npm run up
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test?sslmode=disable
